### ISSUE TITLE
Struggeling to build it on windows

### ISSUE THREAD

**Issue by Tsopic** [krakenjs/grumbler#6]
I had to install many dev dependencies by hand. 

Currently it fails with running command `npm run build`

Errors:

```
 Error ----------------------------------------------------------------------------------------- test/tests/button.js:7:1

Cannot resolve name `describe`.

   7| describe('button cases', () => {
      ^^^^^^^^

Error ----------------------------------------------------------------------------------------- test/tests/button.js:9:5

Cannot resolve name `it`.

   9|     it('should create a button and listen for a click', (done) => {
          ^^

```

**Comment by Tsopic** [comment]
One additional problem one may encounter

 ```
babel-node --plugins=transform-es2015-modules-commonjs ./node_modules/.bin/webpack --progress

D:\Webstorm\project\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Webstorm\project\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at Object.<anonymous> (D:\Webstorm\project\node_modules\babel-cli\lib\_babel-node.js:154:22)

```

Looks like it is tring to use the webpack .sh when it should be using .cmd on windows.

**Comment by Tsopic** [comment]
Gone through installing Ubuntu VM to get this thing going.

`npm run setup `
How to include the script correctly?

Is returning following error.

```
> flow-typed install

• Found 2 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
• Installing 1 libDefs...
  • flow-bin_v0.x.x.js
    └> ./flow-typed/npm/flow-bin_v0.x.x.js
flow-bin
/home/tsopic/test-button/flow-typed/npm
• Generating stubs for untyped dependencies...
  • grumbler-scripts@^1.0.0
    └> flow-typed/npm/grumbler-scripts_vx.x.x.js

!! No flow@v0.66.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

I've generated `any`-typed stubs for this package, but consider submitting 
a libdef for it to https://github.com/flowtype/flow-typed/

```

**Comment by imroca** [comment]
One would expect to setup a clean install and run what the instructions point out and run, but it's not the case, so what a i ended up doing is added this line to my .flowconfig

[ignore]
.*/node_modules/babel-plugin-flow-runtime
.*/node_modules/flow-runtime
.*/node_modules/npm
.*/node_modules/config-chain/test/broken.json
.*/test

@bluepnume afaik you are the one responsible for this repo, could you be so kind to shed some light over this issue?

This is what a have done:

1) git clone https://github.com/krakenjs/grumbler.git some_cool_frontend_project_name
2) yarn install
3) yarn build
--- Some problem with npmlog
4) yarn add npmlog
5) yarn build
--- Same problem as OP.

**Comment by bluepnume** [comment]
@imroca -- after you `npm install` are you running `npm run flow-typed`? And if so can you share the specific error you're seeing?
