### ISSUE TITLE
Is this the repo for jsx-pragmatic ?

### ISSUE THREAD

**Issue by danielpza** [krakenjs/grumbler#7]
The homepage of [this package](https://www.npmjs.com/package/jsx-pragmatic) in npm leads me here, but it has a different name and a different readme

**Comment by bluepnume** [comment]
Whoops no -- this is the correct repo: https://github.com/krakenjs/jsx-pragmatic -- I'll fix that reference.

**Comment by bluepnume** [comment]
Fixed.
